Slack file upload plugin feature
drone-plugins/drone-slack pull request #174
Opened 2024-11-01 13:54 UTC by senthilhns

This code changes implement file upload on Slack using slack go

Following changes done
Bumped up github.com/slack-go/slack package to v0.15.0
Slack file upload plugin feature added
README documented for slack file upload usage
Unit test case for file upload added

Pipeline testing completed, pipeline id: slack_file_send_senthil02

2024-11-05 13:25 UTC, Ompragash requested changes

2024-11-05 13:25 UTC, Ompragash commented on test/UnitTestDockerfile
to be removed

2024-11-05 13:25 UTC, Ompragash commented on plugin.go
> +}
```suggestion
```

we don't have to create a new file for DRONE_OUTPUT

2024-11-05 13:25 UTC, Ompragash commented on plugin.go
> +}
```suggestion
func WriteEnvToOutputFile(key, value string) error {
	outputFile, err := os.OpenFile(os.Getenv("DRONE_OUTPUT"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("failed to open output file: %w", err)
	}

	defer outputFile.Close()

	_, err = fmt.Fprintf(outputFile, "%s=%s\n", key, value)
	if err != nil {
		return fmt.Errorf("failed to write to env: %w", err)
	}

	return nil
}
```

2024-11-06 04:54 UTC, senthilhns commented on test/UnitTestDockerfile
done

2024-11-06 07:17 UTC, Ompragash commented on plugin.go
> +	return int(fileInfo.Size()), nil
```suggestion
	fileInfo, err := os.Stat(filePath)
	if err != nil {
		return 0, fmt.Errorf("failed to get file info: %w", err)
	}
	if fileInfo.IsDir() {
		return 0, fmt.Errorf("path %s is a directory, not a file", filePath)
	}
	return int(fileInfo.Size()), nil
```

2024-11-06 13:06 UTC, Ompragash commented on README.md
> +## Upload files on Slack Usage
```suggestion
## Upload files to Slack
```

2024-11-06 14:02 UTC, merged